name: CLI Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  linux-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set package version
        run: sed -i 's/^version = .*/version = "'${GITHUB_REF##*/v}'"/' Cargo.toml

      - name: Setup Rust
        run: |
          rustup toolchain install stable
          cargo install cross

      - name: Build Release (${{ matrix.target }})
        run: |
          cross build --release --target ${{ matrix.target }}
          mv target/${{ matrix.target }}/release/cli bismuthcli.${{ matrix.target }}

      - name: Upload Release (${{ matrix.target }}) Binaries
        uses: softprops/action-gh-release@v2
        with:
          files: bismuthcli.${{ matrix.target }}

  macos-build-push:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set package version
        run: sed -i '' 's/^version = .*/version = "'${GITHUB_REF##*/v}'"/' Cargo.toml

      - name: Setup Rust
        run: |
          rustup toolchain install stable
          rustup target add ${{ matrix.target }}

      - name: Build Release (${{ matrix.target }})
        run: |
          cargo build --release --target ${{ matrix.target }}
          mv target/${{ matrix.target }}/release/cli bismuthcli.${{ matrix.target }}

      - name: Upload Release (${{ matrix.target }}) Binaries
        uses: softprops/action-gh-release@v2
        with:
          files: bismuthcli.${{ matrix.target }}

  update-version-page:
    runs-on: ubuntu-latest
    needs: [linux-build-push, macos-build-push]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Write version
        run: |
          mkdir static
          echo "${GITHUB_REF##*/v}" > static/LATEST
          echo "<html><body><a href=\"https://github.com/BismuthCloud/cli/releases\">Download the CLI here</a><!-- ${GITHUB_REF##*/v} --></body></html>" > static/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: static
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
